### ISSUE TITLE
Update the project

### ISSUE THREAD

**Issue by VitalyV** [Onebeld/Regul#1]
Hi there!
You have a very cool and rich project, from which a beginner can emphasize a lot of interesting things.
But in the latest versions of Avalonia, the interfaces have been changed. 
Do you have the opportunity to update all the packages in the project and make the appropriate changes? 
Thank you.

**Comment by Onebeld** [comment]
Hi!
Unfortunately, probably not, as I have stopped developing this project. It took too long to develop and is too complicated for beginners to understand. Instead, I am concentrating on programs that perform one task rather than several at once.

**Comment by VitalyV** [comment]
Understood you. 
Thank you for taking the time to respond.
Good luck!
